import { business, bookingUrl } from '../lib/business';
import { categories, type Category } from '../lib/services';
export function Photo({name,alt,className='',priority=false}:{name:string;alt:string;className?:string;priority?:boolean}){return <picture className={className}><source srcSet={`/images/${name}-640.webp 640w, /images/${name}.webp 1280w`} sizes="(max-width: 600px) 90vw, (max-width: 900px) 50vw, 40vw" type="image/webp"/><img src={`/images/${name}.webp`} alt={alt} width={name==='hero-beauty-salon'?1280:1024} height={name==='hero-beauty-salon'?853:1536} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/></picture>}
export function SectionHeading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function TreatmentCard({category,index}:{category:Category;index:number}){return <a className="treatment-card" href={`/treatments/${category.slug}`}><div className="card-photo"><Photo name={category.image} alt={category.alt}/><span className="card-number">0{index+1}</span><span className="round-arrow" aria-hidden="true">↗</span></div><div className="card-body"><h3>{category.name}</h3><p>{category.subtitle}</p><span className="card-link">View Treatments ↗</span></div></a>}
export function TreatmentGrid({limit}:{limit?:number}){return <div className="treatment-grid">{categories.slice(0,limit).map((c,i)=><TreatmentCard key={c.slug} category={c} index={i}/>)}</div>}
export function PriceList({category}:{category:Category}){return <div className="price-list">{category.treatments.map(t=><div className="price-row" key={t.name}><div><h3>{t.name}</h3>{t.description&&<p>{t.description}</p>}</div><strong>£{t.price}</strong><a href={bookingUrl(`${category.name}: ${t.name}`)} aria-label={`Enquire about ${t.name}, £${t.price}`} className="price-book">Book <span aria-hidden="true">↗</span></a></div>)}</div>}
export function CTASection(){return <section className="cta"><p className="eyebrow">MAKE A LITTLE TIME FOR YOU</p><h2>Your next beauty moment<br/><em>starts here.</em></h2><p>Have a treatment in mind, or need a little guidance?<br/>We’d love to hear from you.</p><div className="actions"><a className="button" href={bookingUrl()}>Book Appointment ↗</a><a className="button outline" href={business.telephone}>Call Us</a></div></section>}
export function Benefits(){return <section className="section benefits"><SectionHeading eyebrow="THE NG BEAUTY EXPERIENCE" title="Care in every little detail."/><div className="benefit-grid">{[['01','Personalised Care','Time to discuss your preferences and choose a treatment with you.'],['02','Wide Range of Treatments','Facials, skin treatments and everyday beauty, all in one place.'],['03','Welcoming Environment','A friendly space to settle in and enjoy a moment for yourself.'],['04','Convenient Hyde Location','Find us on Sgt Mark Stansfield Way in Hattersley, Hyde.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>}
export function PageHero({label,title,copy}:{label:string;title:string;copy:string}){return <section className="page-hero"><p className="eyebrow">{label}</p><h1>{title}</h1><p>{copy}</p></section>}
export function Footer(){return <><footer className="footer"><div className="footer-grid"><div><a href="/" className="brand"><img src="/images/logo.jpg" width="68" height="68" alt="NG Aesthetics & Beauty Lab logo"/><span>NG Aesthetics<small>& BEAUTY LAB</small></span></a><p>Beauty & aesthetic treatments<br/>in Hattersley, Hyde.</p></div><div><h2>Explore</h2><div className="footer-links">{[['Home','/'],['About','/about'],['Treatments','/treatments'],['Prices','/prices'],['Gallery','/gallery'],['Contact','/contact']].map(([n,u])=><a href={u} key={u}>{n}</a>)}</div></div><div><h2>Come say hello</h2><p>{business.address}</p><a className="footer-phone" href={business.telephone}>{business.phone}</a></div><div><h2>A little daily inspiration</h2><a href={business.instagram}>{business.instagramHandle} ↗</a><p>Follow along on Instagram.</p></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} {business.name}. All rights reserved.</p><div><a href="/privacy">Privacy Policy</a><a href="/cookies">Cookie Policy</a><a href="/terms">Terms</a></div></div></footer><a className="whatsapp-float" href={bookingUrl()} aria-label="Enquire on WhatsApp"><span aria-hidden="true">◌</span><span>Let’s chat</span></a></>}
// Enable only when genuine, approved customer reviews are supplied. Never publish fabricated reviews.
export function Testimonials({reviews=[]}:{reviews?:{name:string;quote:string}[]}){if(!reviews.length)return null;return <section className="section"><SectionHeading eyebrow="YOUR KIND WORDS" title="What Our Clients Say"/><div className="benefit-grid">{reviews.map(r=><blockquote key={r.name}><p>{r.quote}</p><cite>{r.name}</cite></blockquote>)}</div></section>}
