export type Treatment = { name: string; price: number; durationMinutes: number; description?: string };
export type Category = { slug: string; name: string; subtitle: string; description: string; image: string; alt: string; note?: string; treatments: Treatment[] };
export const categories: Category[] = [
{slug:'facials',name:'Facials',subtitle:'A moment for your skin',description:'Explore our facial menu, from a simple appointment to a more indulgent ritual. We will help you choose a treatment to suit your preferences.',image:'facial',alt:'Illustrative photograph of a relaxing facial treatment',treatments:[
{name:'Microneedling Facial',price:45,durationMinutes:60,description:'A microneedling facial appointment. Contact us to discuss suitability.'},
{name:'Microneedling Luxury Facial',price:60,durationMinutes:75,description:'Our luxury microneedling facial option. Enquire about what is included.'},
{name:'Deluxe Hydro Facial',price:80,durationMinutes:75,description:'Our deluxe hydro facial option for a little extra time for yourself.'},
{name:'Hydro Dermabrasion Facial',price:45,durationMinutes:60,description:'A hydro dermabrasion facial appointment tailored through consultation.'},
{name:'Acne Hydro Facial with LED Therapy',price:50,durationMinutes:75,description:'A hydro facial with LED therapy. Discuss your skin and suitability before booking.'},
{name:'Diamond Microdermabrasion with Jelly Mask',price:65,durationMinutes:75,description:'Diamond microdermabrasion paired with a jelly mask.'},
{name:'Mesotherapy Treatment',price:50,durationMinutes:60,description:'Please contact us for treatment details and suitability information.'},
{name:'Basic Dermabrasion Facial',price:35,durationMinutes:45,description:'Our basic dermabrasion facial option.'},
{name:'Gold Facial with 24K Gold Particles',price:45,durationMinutes:60,description:'A facial featuring 24K gold particles.'}]},
{slug:'skin-boosters',name:'Skin Boosters',subtitle:'Skin care, considered',description:'Choose from single appointments or a course of sessions. Talk to us about your preferences and suitability before arranging a treatment.',image:'facial',alt:'Illustrative facial and skin care photograph',note:'Contact us for a consultation to discuss suitability and the details of your treatment.',treatments:[{name:'1 Session',price:90,durationMinutes:45},{name:'2 Sessions',price:180,durationMinutes:45},{name:'3 Sessions',price:250,durationMinutes:45}]},
{slug:'fat-dissolving',name:'Fat Dissolving',subtitle:'Begin with a conversation',description:'Small and large area options are available. A consultation helps us discuss your requirements and whether a treatment is suitable for you.',image:'hero-beauty-salon',alt:'Illustrative private treatment room',note:"Not sure which option is suitable? Contact us before booking and we’ll discuss your treatment requirements.",treatments:[{name:'1 Small Area',price:60,durationMinutes:45},{name:'2 Small Areas',price:100,durationMinutes:60},{name:'3 Small Areas',price:140,durationMinutes:75},{name:'1 Large Area',price:100,durationMinutes:60},{name:'2 Large Areas',price:175,durationMinutes:75},{name:'3 Large Areas',price:250,durationMinutes:90}]},
{slug:'chemical-peels',name:'Chemical Peels',subtitle:'Time to talk skin',description:'Our chemical peel options include Pure Peel, Refresh Peel and Glow Peel. Enquire to discuss the options and suitability for your skin.',image:'facial',alt:'Illustrative beauty and skin treatment photograph',note:'Pure, Refresh and Glow are available options. Individual option prices have not been supplied; please confirm your selected treatment with us.',treatments:[{name:'Chemical Peel',price:60,durationMinutes:45}]},
{slug:'beauty-treatments',name:'Beauty Treatments',subtitle:'The finishing touches',description:'From beautifully shaped brows to lash tinting, make a little space for the details. Explore our Brows & Lashes menu below.',image:'makeup',alt:'Illustrative beauty portrait with defined brows',note:'High Definition Brows includes eyebrow tint, waxing or threading, shaping and makeup. Ask us about any preparation or patch testing needed before your appointment.',treatments:[{name:'Eyebrow Tint',price:6,durationMinutes:15},{name:'Eyelash Tint',price:6,durationMinutes:30},{name:'High Definition Brows',price:20,durationMinutes:60}]},
{slug:'makeup',name:'Makeup',subtitle:'For your special moments',description:'From a celebration to your wedding day, discover party and bridal makeup that feels like you. A bridal trial gives us time to explore your preferred look together.',image:'makeup',alt:'Illustrative elegant occasion makeup portrait',treatments:[{name:'Party Makeup with Lashes',price:30,durationMinutes:60},{name:'Bridal Makeup',price:250,durationMinutes:120},{name:'Bridal Makeup Trial',price:40,durationMinutes:60}]},
{slug:'threading-tinting',name:'Threading & Tinting',subtitle:'Beautifully defined',description:'Choose a full face or focused threading appointment. For eyebrow and eyelash tint prices, explore our Brows & Lashes menu.',image:'makeup',alt:'Illustrative portrait showing detailed brow styling',treatments:[{name:'Full Face Threading including Eyebrows',price:15,durationMinutes:45},{name:'Eyebrow Threading',price:8,durationMinutes:15},{name:'Upper Lip Threading',price:3,durationMinutes:15}]},
{slug:'waxing',name:'Waxing',subtitle:'Your regular beauty ritual',description:'A straightforward menu of face and body waxing appointments in Hattersley, Hyde. Choose the areas you would like to book below.',image:'hero-beauty-salon',alt:'Illustrative clean private beauty treatment room',treatments:[{name:'Full Body Wax, bikini not included',price:50,durationMinutes:120},{name:'Full Legs Wax',price:20,durationMinutes:60},{name:'Half Legs Wax',price:12,durationMinutes:45},{name:'Full Arms Wax',price:12,durationMinutes:45},{name:'Half Arms Wax',price:8,durationMinutes:30},{name:'Full Face with Eyebrows Wax',price:15,durationMinutes:45},{name:'Eyebrow Wax',price:6,durationMinutes:15},{name:'Upper Lip Wax',price:3,durationMinutes:15}]},
{slug:'vitamin-b12',name:'Vitamin B12',subtitle:'Suitability comes first',description:'Please contact NG Aesthetics & Beauty Lab for suitability and consultation information before booking a Vitamin B12 appointment.',image:'hero-beauty-salon',alt:'Illustrative welcoming consultation environment',note:'No health outcomes are promised. Contact us to discuss suitability and appointment information.',treatments:[{name:'1 Shot',price:20,durationMinutes:15},{name:'2 Shots',price:35,durationMinutes:30}]}
];
export const priceDisclaimer = 'Treatment availability and prices may change. Please contact NG Aesthetics & Beauty Lab to confirm your appointment and treatment.';
