import assert from 'node:assert/strict';

globalThis.MessageChannel = undefined;
const { default: worker } = await import('../dist/server/index.js');
const env = { ADMIN_EMAILS: 'admin@example.test', ASSETS: { fetch: async () => new Response('asset') } };
const page = await worker.fetch(new Request('https://example.test/'), env);
assert.equal(page.status, 200);
const html = await page.text();
for (const id of ['home','about','services','booking','gallery','location','reviews','contact']) assert.match(html, new RegExp('id="' + id + '"'));
const adminPage = await worker.fetch(new Request('https://example.test/admin'), env);
assert.equal(adminPage.status, 200);
assert.match(await adminPage.text(), /noindex, nofollow/);
const oldPage = await worker.fetch(new Request('https://example.test/contact'), env);
assert.equal(oldPage.status, 301);
assert.equal(oldPage.headers.get('location'), '/#contact');
const asset = await worker.fetch(new Request('https://example.test/images/logo.jpg'), env);
assert.equal(await asset.text(), 'asset');
const availability = await worker.fetch(new Request('https://example.test/api/availability?month=2026-10'), env);
assert.equal(availability.status, 200);
assert.deepEqual((await availability.json()).slots, []);
const anonymousAdmin = await worker.fetch(new Request('https://example.test/api/admin/overview'), env);
assert.equal(anonymousAdmin.status, 401);
assert.deepEqual(await (await worker.fetch(new Request('https://example.test/api/google-reviews'), env)).json(), { error: 'Not found' });
console.log('PASS: Sites worker, one-page booking UI, protected admin route, API routing, redirects, and static assets.');